name: Win-x64 Build on Push

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Publish
        # Только архитектура и папка. Без сжатия и оптимизаций.
        run: dotnet publish AndromedaDnsFirewall/AndromedaDnsFirewall.csproj -c Release -r win-x64 -p:SelfContained=false -p:PublishSelfContained=false -o ./publish

      - name: Zip Release
        shell: pwsh
        run: Compress-Archive -Path ./publish/* -DestinationPath release-win-x64.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: release-win-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
